// <autogenerated>
//   This file was generated by T4 code generator SampleScriptTemplates.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

namespace Sitecore.CodeGenerator.Sample.Glass.Models
{
	using System;
    using System.Collections.Generic;
	using System.Collections.Specialized;
    using global::Glass.Mapper.Sc.Configuration;
    using global::Glass.Mapper.Sc.Configuration.Attributes;
	using global::Glass.Mapper.Sc.Fields;

	/// <summary>
	/// Represents a mapped type for item {319EB0A2-EF28-4DAE-B35C-551BD53317B2} in Sitecore.
	/// Path: /sitecore/templates/Sitecore Code Generator Sample/Animal
	/// </summary>
	[SitecoreType(TemplateId = "{319EB0A2-EF28-4DAE-B35C-551BD53317B2}")]
	public partial interface IAnimal
	{
		#region Animal

		/// <summary>
		/// A short description of the animal
		/// </summary>
	    [SitecoreField(FieldId = "{EDFD61C6-BBEF-45B6-8FD4-84CA215BAB73}")]
		string Description { get; set; }

		#endregion

	}
}
