// <autogenerated>
//   This file was generated by T4 code generator SampleScriptTemplates.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

namespace Sitecore.CodeGenerator.Sample.Glass.Models
{
	using System;
    using System.Collections.Generic;
	using System.Collections.Specialized;
    using global::Glass.Mapper.Sc.Configuration;
    using global::Glass.Mapper.Sc.Configuration.Attributes;
	using global::Glass.Mapper.Sc.Fields;

	/// <summary>
	/// Represents a mapped type for item {7196E22C-0B26-4539-BAEE-959ED8C5BFE5} in Sitecore.
	/// Path: /sitecore/templates/Sitecore Code Generator Sample/Food
	/// </summary>
	[SitecoreType(TemplateId = "{7196E22C-0B26-4539-BAEE-959ED8C5BFE5}")]
	public partial interface IFood
	{
		#region Nutrition

		/// <summary>
		/// How many calories per serving?
		/// </summary>
	    [SitecoreField(FieldId = "{3F57B9D2-50EC-4F87-8631-2334C837D5BF}")]
		Decimal Calories { get; set; }

		#endregion

	}
}
